### ISSUE TITLE
Do you have an example usage? The docs are unclear.

### ISSUE THREAD

**Issue by andyjessop** [kaisermann/svelte-preprocess#1]
In the readme, you have `svelte.preprocess(input, getSveltePreprocessor()).then(...)`, but it's not clear what `input` is, and what happens in `then`.

I'm interested to see how to use this with the `svelte-loader`.

**Comment by kaisermann** [comment]
That basic example is how you would manually call the `svelte.preprocess` method. 

In case of the loader, just pass a `preprocess: getSveltePreprocessor()` to [`svelte-loader`](https://github.com/kaisermann/svelte-preprocess#with-svelte-loader) options 😀 

I've add a `svelte-loader` example on the [`README.md`](https://github.com/kaisermann/svelte-preprocess#with-svelte-loader).
