### ISSUE TITLE
Add :local selector to global styles

### ISSUE THREAD

**Issue by PatrickG** [kaisermann/svelte-preprocess#103]
**Is your feature request related to a problem? Please describe.**
If, for example, you need to create 20 global selectors and one local selector in a component, it would be nice to have a `:local(...)` selector inside `<style global></style>` declarations.

**Describe the solution you'd like**
I have a simple solution in [my fork](https://github.com/PatrickG/svelte-preprocess/blob/master/src/transformers/globalStyle.js#L10-L11)

**Comment by kaisermann** [comment]
Hey @PatrickG  👋. 

Adding a `:local` makes sense. I'm going to check your fork soon 😁 Thanks!

**Comment by kaisermann** [comment]
`:local()` support was added in version `v3.3.0`. I ended up with a different approach on how to implement this feature which also supports using `:local()` anywhere on a selector, not just at the beginning.

**Comment by PatrickG** [comment]
Nice, thank you.

**Comment by silllli** [comment]
I just noticed that it works when using it as a modifier, but not when nesting other selectors in it (using SASS), as it does with `:global` and how I understood the docs.

> Note4: if you need to have some styles be scoped inside a global style tag, use :local in the same way you'd use :global.

So, this works:

```
:local(.center) {
  text-align: center;
}
```

Whereas this doesn’t:

```
:local {
  .center {
    text-align: center;
  }
}
```

**Comment by kaisermann** [comment]
Hey, @silllli 👋  can you open an issue specific for that?
