### ISSUE TITLE
[svelte-preprocess] Error transforming '0'.

### ISSUE THREAD

**Issue by kapilpipaliya** [kaisermann/svelte-preprocess#105]
https://svelte.dev/repl/ced3c20d393a415195ea87f4262d05b4?version=3.16.5
when i copy above component in sapper route. it gives error: [svelte-preprocess] Error transforming '0'.

**Comment by kaisermann** [comment]
Hey @kapilpipaliya! That's a known limitation of the way svelte looks for the `script` and `style` tags to send them to the preprocessors: https://github.com/kaisermann/svelte-preprocess/issues/96#issuecomment-551772246.
