### ISSUE TITLE
add preval preprocessor to evaluate "static" expressions at compile time

### ISSUE THREAD

**Issue by milahu** [kaisermann/svelte-preprocess#107]
[preval for svelte](https://gist.github.com/milahu/e1cd4aeedda84b77351cf84e10a97c07) is a sample implementation

what it does is, convert at compile time, from
```js
let testPreval = preval(() => ({
  a: Math.PI * 0.5,
  b: Math.sqrt(2),
}))

// unpack object properties to global scope
Object.assign(window, preval(() => {
  return {
    a: Math.PI * 0.5,
    b: Math.sqrt(2),
  }
}))
```
to
```js
let testPreval = {
  "a": 1.5707963267948966,
  "b": 1.4142135623730951
}

Object.assign(window, {
  "a": 1.5707963267948966,
  "b": 1.4142135623730951
})
// window = global scope of browser
// --> a === 1.5707963267948966
```

the samples here are trivial
but generally, its a waste of energy [load time, battery drain]
to eval such "static" expressions on the client side
when they can easily be eval-ed on the compiler side
CSR = compiler side rendering

this also helps in code readability, and avoids "magic numbers"
cos you have the "source formula" colocated with your component
without the cost of a runtime eval

you can also use commonJS modules like
```js
let testPreval = preval(() => {
  const fs = require('fs')
  return fs.readFileSync('input.txt').toString()
})

// result: testPreval === "hello world\n"
```
other module formats could be transformed "on the fly", using

> `npm i --save-dev @babel/core @babel/cli @babel/plugin-transform-modules-commonjs`
> `./node_modules/@babel/cli/bin/babel.js --plugins @babel/plugin-transform-modules-commonjs src/moduleName.js > src/moduleName.cjs`

so please, feel free to include my code in this project
or feel free to wait for my pull request : P

**Comment by kaisermann** [comment]
Hey 👋 Thanks for the idea! However, I don't think it fits very well with the purpose of `svelte-preprocess` and it would probably be better if it was a standalone svelte preprocessor! Even if it fitted, I try very hard to keep this library as small as possible and by adding, for example, [`recast`, we would gain a lot of weight](https://bundlephobia.com/result?p=recast@0.18.5): 

![image](https://user-images.githubusercontent.com/12702016/71861732-1b74de80-30d6-11ea-869c-e892d50e4b72.png)

**Comment by milahu** [comment]
thanks for response : ]

> the purpose of svelte-preprocess

from svelte, give access to other preprocessors?
yes, then this is out-of-scope

for the record, i found

* [estree-walker](https://github.com/Rich-Harris/estree-walker) as AST tree walker
* [astring](https://github.com/davidbonnet/astring) as AST printer / JS code generator

who can do the same work for only 1 + 14 = 15 KiloByte, and probably faster
where recast needs 300 KiloByte

full bundle size
* 80 lines-of-code [sveltePreval.js](https://gist.github.com/milahu/e1cd4aeedda84b77351cf84e10a97c07)
* 14 KB astring
* 8 KB lave

22 KB total

acorn, estree-walker are dependencies of svelte
