### ISSUE TITLE
Add Reasonml Language

### ISSUE THREAD

**Issue by Gracrys** [kaisermann/svelte-preprocess#109]
**Is your feature request related to a problem? Please describe.**
No, is not related to some problem, but an idea

**Describe the solution you'd like**
I m interested in using this package and compiling to reasonml, the same way you use lang=typescript or coffe, but i dont know how to start 😅

**How important is this feature to you?**
I would like to use this new feature in production

**Comment by kaisermann** [comment]
Hey @Gracrys 👋 I'm not familiar with `ReasonML` and if it provides a JS API which can compile `ReasonML` from memory to a JS string, but you'd do something akin to:

```js
// i.e rollup.config.js
import preprocess from 'svelte-preprocess'
import { compileReasonToJs } from 'reasonMLCompiler'

preprocess({
  aliases: [
    // link .re to reason language
    ['re', 'reason'],
  ],

  /** Add a reasonML preprocessor */
  async reason({ content, filename }) {
    const { output, sourcemap } = await compileReasonToJs(content)

    return {
      code: output,
      map: sourcemap,
    }
  },
})   
```

**Comment by Gracrys** [comment]
ok, i see, will try to find some JS Api, and work around it, thanks!

**Comment by mloureiro** [comment]
@Gracrys did you found a way?

From what I can see, we can easily setup the BuckleScript to convert ReScript (ReasonML) to Javascript, and then the normal processes will work.
Although, this won't matter much, as the main benefit are the type system (as they did for React,  [Reason React] (https://github.com/reasonml/reason-react/)).

As a noobie starting with ReasonML, I have no idea how much effort is needed to make this layer in between.

**Comment by Sajjon** [comment]
[This issue](https://github.com/sveltejs/svelte/issues/6020) might be relevant for anyone interesting in using Svelte + ReScript (no working example to look at at the moment, but [someone got something working](https://github.com/sveltejs/svelte/issues/6020#issuecomment-785402276))

**Comment by Gracrys** [comment]
Nop, i couldnt find the way to connect the js api to the svelte, in fact not even find the js api, i also started working with typescript so....  😅
