### ISSUE TITLE
Trying to add a custom preprocessor doesn't appear to work

### ISSUE THREAD

**Issue by antony** [kaisermann/svelte-preprocess#11]
I'm trying to implement [google structured data](https://codelabs.developers.google.com/codelabs/structured-data/index.html#3)

However, upon trying to stop the plugin from processing these blocks of JSON, I think I've discovered that a custom compiler is not loaded correctly:

My configuration is as follows:

```js
{
  transformers: {
    scss: {
      includePaths: [
        'node_modules',
        'src'
      ]
    },
    structuredData ({ content }) {
      return { code: content, map: '' }
    }
  },
  aliases: [
    ['application/ld+json', 'structuredData']
  ]
}
```

However, upon booting the app, I think it is trying to resolve the compiler incorrectly:

```bash
Error: Module build failed (from ./node_modules/svelte-loader/index.js):
Error: [svelte-preprocess] Error transforming 'structuredData'. Message:
Cannot find module './transformers/structuredData.js'
    at Object.exports.throwError.msg [as throwError] (/home/ant/Projects/beyonk-sapper/node_modules/svelte-preprocess/src/utils.js:25:9)
```

I expect it to use the function specified in `transformers` rather than try to load it from disk.

**Comment by kaisermann** [comment]
Fixed on `v2.4.1` 🎉
