### ISSUE TITLE
Parcel, Svelte & Autoprefixer ?

### ISSUE THREAD

**Issue by vexkiddy** [kaisermann/svelte-preprocess#113]
Hi again, this is more of a question as I can't seem to find any working examples. I'm struggling with trying to get Autoprefixer to work with Svelte and Parcel inside of `svelte-preprocess`. I've tried all of the suggested methods but whatever I do I'm not seeing browser prefixes when I compile for dev. I can supply a repro if you think you might be able to help? :D

**Comment by kaisermann** [comment]
Hello again 👋 You just need to add `postcss: { ... }` to the main option object:

```js
// example
preprocess({
 postcss: {
    plugins: [require('autoprefixer')({ browsers: 'last 2 versions' })],
  },
}

```
Yeah, a repo always helps!

**Comment by vexkiddy** [comment]
hiya! thanks! yep... i've done that and it now works but this then throws an autoprefixer error that i've raised here : https://github.com/postcss/autoprefixer/issues/1282.. any ideas ?

**Comment by kaisermann** [comment]
Unfortunately, no 😞 This seems to be unrelated to `svelte-preproces` so closing it for now 😁
