### ISSUE TITLE
Style overrides

### ISSUE THREAD

**Issue by drop1down** [kaisermann/svelte-preprocess#114]
Lets say i write ui library package.
I can define some variables (colors etc) for my theme.

Someone else want to use my library.
But he need to modify/fork my lib.

Now my idea:
What if this preprocesser look for a custom style file (if available) in project root and override original package variable values (only in memory, files are untouched).

So custom vars have higher priority than original package vars.

**Comment by kaisermann** [comment]
I'd recommend you to use css vars if possible. However, you can configure i.e the sass preprocessor to import your override file before every read sass file.

```js
{
    scss({
        data: `@import "${process.cwd()}/src/override.scss"`
    })
}
```

What's passed to the `data` property is prepended to every scss file.
