### ISSUE TITLE
SASS not working

### ISSUE THREAD

**Issue by drop1down** [kaisermann/svelte-preprocess#116]
I was able to use SCSS,
but SASS (=old syntax) do not work?

App.svelte
```
<style lang="sass">
.demo
	background-color: #f00
	width: 100px
	height: 100px
</style>
<div class="demo">???</div>
```

rollup.config.js:
```
import {sass} from 'svelte-preprocess'
.....
	plugins: [
		svelte({
			preprocess: [
				sass({})
			],
.....
```

ERROR:

Invalid CSS after ".demo {": expected "}", was "{"

**Comment by GitGangGuy** [comment]
You might want to try Stylus instead

**Comment by marcebdev** [comment]
Can confirm, using Sapper I got further than you but the formatter when used with the VSCode Svelte plugin breaks on id's and classnames. In my case its the formatter but looks like it's not going to work unfortunately.

Likely going to have to use Stylus or SCSS

**Comment by kaisermann** [comment]
Where is this error appearing? Is it preventing your compilation or is it shown in your IDE? I just tried adding `sass` to the `examples/svelte-rollup` app in this repo, pasted your component in the `App.svelte` and it compiled without issues.
