### ISSUE TITLE
PostCSS imported variable resolution issues.

### ISSUE THREAD

**Issue by TimothyDespair** [kaisermann/svelte-preprocess#119]
**Describe the bug**
When importing variables from a SugarSS formatted file using the postcss preprocessor they can not be resolved. The running postcss on the same SugarSS produces expected output just fine. This despite using the exact same config.

**Error Log**
```
$ rollup -c -w
rollup v1.32.0
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) CssSyntaxError: precss: /Users/tim/Development/svelte-preprocess-bug/src/test2.sss:2:11: Could not resolve the variable "$yellow" within "div
  color: $yellow"
```

**To Reproduce**
[Demo Repo](https://github.com/TimothyDespair/svelte-preprocess-bug)

Run `yarn postcss` to run postcss compile (you'll get the output). Run `yarn svelte` to rollup the tiny svelte project with the same css (you'll hit an error).

**Expected behavior**
Same results from svelte-preprocess as postcss running directly.

**What I tried**
Tried adding `rollup-plugin-postcss` to see if that might help as it did in [Issue #75](https://github.com/kaisermann/svelte-preprocess/issues/75). Didn't change anything, (I expect because I am importing and so it should be handled by `svelte-preprocess` but thought it was worth a shot.)

**Comment by TimothyDespair** [comment]
Interestingly the issue goes away and everything compiles fine when including the PostCSS file with:

```
<style lang="postcss" src="test.sss"></style>
```

**Comment by TimothyDespair** [comment]
Additional point of data: the same example with PostCSS works fine, it's only SugarSS that upsets it.

**Comment by TimothyDespair** [comment]
Solved!

I was using the string options in my post css config.

Switched to the function options and requiring all the packages and now it works fine. Have pushed working version to the repo for anyone who wants to see.

**Comment by kaisermann** [comment]
Great to know @TimothyDespair! I will give a check why the string option wasn't working anyway!
