### ISSUE TITLE
You can only have one top-level <style> tag per component

### ISSUE THREAD

**Issue by GitGangGuy** [kaisermann/svelte-preprocess#120]
**Describe the bug**
I personally use LESS, but the Svelte Material UI (SMUI) library I'm utilizing uses SASS as a CSS preprocessor. When trying to use multiple `<style>` tags with different languages (`lang="less"` and `lang="sass"`), it won't compile because svelte/(sapper in my case) doesn't accept multiple top-level style tags.

**Logs**
`You can only have one top-level <style> tag per component` (from rollup->client and ->server)

**To Reproduce**
Default sapper project template with multiple preprocessor <style> tags in an component.

**Expected behavior**
It should compile both without throwing an error.

**Information about your project:**

- Your browser and the version: -

- Your operating system: Windows 10 Pro

- `svelte-preprocess` version `^3.4.0`

- Rollup

**Comment by GitGangGuy** [comment]
By the way I love this plugin, keep up the good work! 💖  
I know maintaining stuff like this can be difficult, so thank you for taking your time investigating on this issue!

**Comment by kaisermann** [comment]
Hey @GitGangGuy! Unfortunately, that's a Svelte limitation. I could mimic the exact process it does to capture the tags and their contents, but not only this would be happening twice, I'd need to literally replicate the preprocess step from the compiler's side.
