### ISSUE TITLE
Manually add processors to reduce dependency load

### ISSUE THREAD

**Issue by blynx** [kaisermann/svelte-preprocess#122]
This is  not really an issue-issue, but I like the idea of keeping dependencies as low as possible.  
There is sass, typescript, coffeescript, less, postcss, soon babel, etc ... all directly bundled, but one probably only uses half of the processors.

What do you think about that users would have to add processors manually just when they use them? You'd get a warning while building and used processors are missing.

This is not critical, but something I personally would like to see.  
Curious about your opinion :)

thanks!

**Comment by kaisermann** [comment]
Hey @blynx 👋 that IS a great idea and that's why the lib already does that since it's birth 😁 Check the readme [here](https://github.com/kaisermann/svelte-preprocess/blob/master/README.md#installation) to see it. There's also a ll`postinstall` log that tries to alert about this.

**Comment by blynx** [comment]
😀 omg of course 🙈

Thats awesome, thanks for the quick reply!  
I guess this issue can be closed then ^~^
