### ISSUE TITLE
Eslint doesn't take built-in pug mixins into account

### ISSUE THREAD

**Issue by SqrtMinusOne** [kaisermann/svelte-preprocess#131]
**Describe the bug**
I have encountered a problem with eslint & pug templates. In this code:
```pug
ul
  +each('rowData as row')
    li { row.make }, { row.model }, { row.price }
```
The following errors are found (at least with my configuration of eslint):
```
  14:10  warning  'row' is not defined  missing-declaration
  14:10  error    'row' is not defined  no-undef
  14:24  warning  'row' is not defined  missing-declaration
  14:24  error    'row' is not defined  no-undef
  14:39  warning  'row' is not defined  missing-declaration
  14:39  error    'row' is not defined  no-undef
```
The code in the curly braces is linted as it should be, but the code in the mixin isn't.

**To Reproduce**
Try to lint the given code with the following config of eslint:

```javascript
module.exports = {
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: 'module',
    parser: 'babel-eslint'
  },
  env: {
    es6: true,
    browser: true,
    node: true,
  },
  extends: ["eslint:recommended", "standard"],
  plugins: [
    'pug',
    'svelte3',
  ],
  ignorePatterns: ["__sapper__/", "node_modules/", "src/node_modules/"],
  overrides: [
    {
      files: ['**/*.svelte'],
      processor: 'svelte3/svelte3',
      rules: {
        'import/first': 'off',
        'import/no-duplicates': 'off',
        'import/no-mutable-exports': 'off',
        'import/no-unresolved': 'off'
      }
    }
  ],
}
```
**Expected behavior**
The code in the mixins should be linted as well.

Is there any way to fix this? I don't want to turn off the `no-undef` rule.

**Information about your project:**
eslint packages:
```javascript
   "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.1",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-pug": "^1.2.2",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-svelte3": "^2.7.3",
```
Svelte-preprocess version: 3.7.1

OS, editor: Linux Mint 19.3, neovim & ALE.

The project uses webpack, if that somehow has an effect.

Edit: edited the issue according to the bug report template. Haven't noticed it first.

**Comment by kaisermann** [comment]
Hey @SqrtMinusOne :wave: Thanks for detailing your issue! Unfortunately, this is happening because svelte's eslint plugin doesn't support preprocessors yet (see it here https://github.com/sveltejs/eslint-plugin-svelte3/issues/10). It's able to recognize those `{row...}` expressions because it parses it as plain html text.
