### ISSUE TITLE
@import-ed file on save doesn't reload with Rollup

### ISSUE THREAD

**Issue by frederikhors** [kaisermann/svelte-preprocess#142]
**Describe the bug**
I don't know if this is the right repo to open this. Maybe I should on svelte. I don't really know.

I wanna report that when I save an imported .scss file rollup doesn't reload at all.

**To Reproduce**

- App.svelte

```svelte
<style global lang="scss">
  @import './scss/index.scss';
</style>

<main>
...
</main>
```

- rollup.config.js

```js
const preprocessOptions = {
  scss: { includePaths: ['src', 'node_modules'] },
  postcss: {
    plugins: [
      autoprefixer
    ].filter(plugin => plugin)
  }
}
const preprocess = autoPreprocess(preprocessOptions)

export default {
  ...

  plugins: [
    svelte({
      dev: !production,
      css: css => css.write('main.css', sourcemap),
      preprocess
    }),
    
    ...

    !production && livereload(distFolder)
  ],
  watch: {
    clearScreen: false,
    include: 'src/**'
  }
}
```

**Expected behavior**
When I save something in `index.scss` rollup should reload my app in browser.

Every other file (js, css, scss, svelte) works.

**Information about your project:**

- Your browser and the version: Chrome 81

- Your operating system: Windows 10

- `svelte-preprocess` version 3.7.4

- Rollup 2.7.6

**Comment by benmccann** [comment]
Are you using https://github.com/rixo/rollup-plugin-svelte-hot?

**Comment by frederikhors** [comment]
It works now.
