### ISSUE TITLE
Rollup watch not working with external files.

### ISSUE THREAD

**Issue by PaulMaly** [kaisermann/svelte-preprocess#20]
Seems, if we use external files, changes in this files not perform re-building process.

**Comment by kaisermann** [comment]
Can you make a quick repro repository? :grin:

**Comment by kaisermann** [comment]
`scss` and `postcss` imports (via `postcss-import`/`postcss-easy-import`) are now supported on `v2.7.1`. 

When I get a little of free time again I'll look on how to add this to other processors as well.
