### ISSUE TITLE
scriptTransformer doesn't resolve the external script the right way

### ISSUE THREAD

**Issue by eBaeza** [kaisermann/svelte-preprocess#22]
I'm using a component like that

```html
...
<script src="./Component.js"></script>
<style src="./Component.scss"></style>
```

But when i run the webpack command seems that the scriptTransformer is not sync up between filename and the attirbute.src, every time that i run the command the filename changes so i get an error 

```console
Error: ENOENT: no such file or directory, open ...src\\components\\moreComponents\\Component.js
```

and that's right because it searchs the file in the incorrect path.

So, i print a log in the `getTransformerTo` function and i can see desyncrhonized the filename and the attribute.src when  the language to transform is `javascript`.

```console
[ 
  'scss',  // lang
  '...src\\components\\Component\\Component.html', // filename
  './Graph.scss', // attribute.src
  '...src\\components\\Component\\Component.scss' // resolveSrc(...)
]
[ 
  'javascript', // lang
  '...src\\components\\moreComponents\\OtherComponent.html', // filename
  './Component.js', // attribute.src
  '...src\\components\\moreComponents\\Component.js' // resolveSrc(...)
]
```

**Comment by kaisermann** [comment]
Can you provide a quick repro repository? I'm unable to reproduce your error.

**Comment by eBaeza** [comment]
@kaisermann it happens in a project with 100+ components, and just around 5-6 are using the external .js and .scss of wich only 2 have this problem

**Comment by kaisermann** [comment]
@eBaeza I'm sorry, but I'm unable to reproduce your error and without a way to reproduce it I can't find what's wrong.

**Comment by eBaeza** [comment]
@kaisermann don´t worry i think it´s a problem with svelte-loader, i switch to rollup, and svelte-preprocess works fine. Thanks!

**Comment by kaisermann** [comment]
@eBaeza 🎉 Ok, great! 🎉
