### ISSUE TITLE
Example for Rollup Plugin Svelte

### ISSUE THREAD

**Issue by quarksplitter** [kaisermann/svelte-preprocess#26]
Hi, 

would you be able to provide an example on how to use `svelte-preprocess` with `rollup-plugin-svelte`?

Thanks a lot!

**Comment by kaisermann** [comment]
Sure! There you go: https://github.com/kaisermann/svelte-preprocess#with-rollup-plugin-svelte 🙌

**Comment by quarksplitter** [comment]
Thanks a lot :)

**Comment by flekschas** [comment]
@kaisermann What are you doing to get the array notation to work? I am getting a `(svelte plugin) ParseError: Unexpected input` error, which I assume is related to https://github.com/rollup/rollup-plugin-svelte/issues/51? Maybe I am doing something wrong? My setup is essentially the same as what you described:

```js
// rollup.config.js
import svelte from 'rollup-plugin-svelte';
import { scss } from 'svelte-preprocess'

export default {
  ...,
  plugins: [
    svelte({
      preprocess: [scss()]
    })
  ]
}
```

I am using:
- rollup-plugin-svelte `v5.0.3`
- svelte-preprocess `v2.9.0`
- node-sass `v4.12.0`

**Comment by kaisermann** [comment]
Hmmmm, very strange. I just tried this on this repo `example/rollup` directory and it worked without problems. Could you provide a quick repro?

**Comment by flekschas** [comment]
The setup in `example/rollup` is the one I am using right now, which uses `preprocess: autoProcess({ ... })` (e.g., [line 22](https://github.com/kaisermann/svelte-preprocess/blob/master/examples/rollup/rollup.config.js#L22)).

As far as I understood the Readme we should also be able to do `preprocess: [scss()]`

> It is also possible to manually enqueue stand-alone processors
> ```
>  preprocess: [
>    pug({ /* pug options */ }),
>    scss({ /* scss options */ }),
>    coffeescript({ /* coffeescript options */ })
>  ]
> ```
I've adjusted the example and can reproduce the error: https://github.com/flekschas/svelte-preprocess/blob/master/examples/rollup/rollup.config.js#L22

**Comment by kaisermann** [comment]
Yeah, I've modified to use it the `scss` but I didn't get any error. HOWEVER.... your repro is indeed throwing an error and I think it's the `rollup-plugin-svelte`'s fault. I will try to fix it and update you here 😉

**Comment by kaisermann** [comment]
There ya go https://github.com/rollup/rollup-plugin-svelte/pull/56

**Comment by flekschas** [comment]
Cool! Thanks for the great support! :)

**Comment by huy-ta** [comment]
Until rollup/rollup-plugin-svelte#56 is successfully merged, I think we should correct https://github.com/kaisermann/svelte-preprocess#with-rollup-plugin-svelte and let people know that [rollup-plugin-svelte](https://github.com/rollup/rollup-plugin-svelte) doesn't work with an array of preprocessors for now? 'Cause it took me a while to find out what was wrong 🤣.

**Comment by kaisermann** [comment]
Yeah, you're right! I'll reopen this issue for the time being just so people can find the problem/solution more easier

**Comment by huy-ta** [comment]
@kaisermann Any news on this? I think rollup/roolup-plugin-svelte#56 is pretty much completed.

**Comment by kaisermann** [comment]
@huy-ta yep, was merged and released 🎉
