### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by UnwrittenFun** [kaisermann/svelte-preprocess#27]
I am thinking about using this module to add easy, built in support for other languages in the [vscode plugin](https://github.com/UnwrittenFun/svelte-vscode) / [language server](https://github.com/UnwrittenFun/svelte-language-server). Would be great to have typescript support out of the box just using this module.

I'm happy to make a PR for it 🙂

**Comment by kaisermann** [comment]
I've been planning to give it a try but I currently don't have much free time :sob: A PR would be great!
