### ISSUE TITLE
Sapper Typescript Pug Example

### ISSUE THREAD

**Issue by burner** [kaisermann/svelte-preprocess#31]
I'am trying to get sapper with rollup to work with typescript and pug, but I just can't wrap my head around the build process.

Is there any change to get a example with the above mentioned tech?

Thank you

**Comment by laurentpayot** [comment]
Regarding Pug, you have to use mixins. Maybe answer can help you: https://stackoverflow.com/a/51809972/2675387

**Comment by burner** [comment]
maybe need to clarify. You don't even get the start sapper project to compile with pug and ts. I don't use and svelte html control structures at this point.

**Comment by burner** [comment]
might also be helpful to have the example rollup.config.js close to the one generated by sapper rollup.config.js

**Comment by kaisermann** [comment]
@burner to preprocess pug and typescript you should just install `typescript`, `pug`, `import preprocess from 'svelte-preprocess'` and pass it to the svelte `preprocess` option:

```
preprocess: preprocess()
```

For typescript, you should also config your `tsconfig.json`.

Once I get some spare time I'll provide a sapper example in the `examples` directory 👍

**Comment by burner** [comment]
@kaisermann thank you for coming back to me. 
I created a PR that shows where I want to go with this.

**Comment by kaisermann** [comment]
@burner Sapper example was added 🎉

**Comment by burner** [comment]
@kaisermann thank you very much. I still got a problem though.
/blog gives me
```
preprocess/examples/sapper_ts_pug_scss/src/routes/blog/index.svelte
'posts' is not defined
```

The page shows a 500 with 
```
ReferenceError: posts is not defined
```
