### ISSUE TITLE
How to use scss?

### ISSUE THREAD

**Issue by gluaxspeed** [kaisermann/svelte-preprocess#35]
```html
<style lang="scss">
:global(a.active) {
    color: crimson;
}

$test: green;
h1 {
    color: $test;
}
</style>
```

This is giving me an error **(svelte plugin) ParseError: Selector is expected** and I am not sure what I am doing wrong? In my rollup.config.js I have the following...

``` js
export default {
	input: 'src/main.js',

	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/bundle.js'
	},
	
	plugins: [
		svelte({
			preprocess: [scss()],

			dev: !production,

			css: css => {
				css.write('public/bundle.css');
			},
		}),

		resolve(),
		commonjs(),

		!production && livereload('public'),
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};
```

Is there something else I should be doing? And if so can we provide more clear instructions or links to where I could learn how to use this?

**Comment by evnix** [comment]
Did you figure out the issue?

**Comment by gluaxspeed** [comment]
I did eventually figure out the issue, although I don't remember how I resolved it. I winded up just using a different package known as svelte-preprocess-sass as I was only interested in the sass part of this project.

**Comment by evnix** [comment]
Thank You! the other one worked straight way!
