### ISSUE TITLE
SASS is not equivalent to SCSS

### ISSUE THREAD

**Issue by lukeed** [kaisermann/svelte-preprocess#4]
Hey~! 

I really like this package, super useful for getting set up quickly 👏 I'm using it within [`@pwa/preset-svelte`](https://github.com/lukeed/pwa/tree/master/packages/preset-svelte) because it's so handy.

Quick issue – I'll get around to fixing it soon, but can't quite yet:

Processing SASS isn't the same as processing SCSS files. You need to have `indentedSyntax: true` when using SASS.

Easiest (worst) solution is to just add copy the `transformers/scss` file and hardcode the change.

The better & more extensible solution would be to lookup any aliased/direct matches on the `transformers` object for additional configuration. Eg, adding this as the default:

```js
transformers: {
  sass: { indentedSyntax: true }
}
```

...then pass that addl config to `transformers/scss` directly.

Thanks!

**Comment by kaisermann** [comment]
@lukeed Your wish is a order 👏 As of release `v2.3.0` you can pass specific options to aliased languages.

And thanks! I'm glad to know this is helping somebody else 😁!

**Comment by lukeed** [comment]
Awesome, thank you! Not an order though 😂

This totally works for me, but I still think `sass` should be hard-coded with the indented option, as that's a required for the extension to work.

**Comment by kaisermann** [comment]
I know heh, I'm just happy to help 🙊 

You're totally right. It makes no sense to force someone to define the `sass` property just for that. Released as `v2.3.1` 🎉

**Comment by lukeed** [comment]
Awesome – thank you @kaisermann ! 🙇
