### ISSUE TITLE
Example for Sapper apps

### ISSUE THREAD

**Issue by bekliev** [kaisermann/svelte-preprocess#40]
New chapter in the docs for: "how to connect the plugin in sapper apps" - would be so useful.

In Sapper ([sapper-template](https://github.com/sveltejs/sapper-template)) apps there are 2 configs for: client and server.

So to make it work on server and client, people have to add to server config too, like this:
<details>
<summary>rollup.config.js (only required lines represented)</summary>

```js
// ...
import autoPreprocess from 'svelte-preprocess';

const svelteCommonOptions = {
  preprocess: autoPreprocess({
    postcss: true, // to use postcss.config.js
  }),
};

export default {
  client: {
    plugins: [
      svelte({
        ...svelteCommonOptions,
        // ...
      }),
  },
  server: {
    plugins: [
      svelte({
        ...svelteCommonOptions,
        // ...
      }),
    ],
  },
};
```
</details>

**Comment by kaisermann** [comment]
Oh, nice suggestion! I added it to the [readme](https://github.com/kaisermann/svelte-preprocess#with-sapper)

Thanks 🎉
