### ISSUE TITLE
Can't make postcss sugarss work

### ISSUE THREAD

**Issue by shamsartem** [kaisermann/svelte-preprocess#43]
I have postcss.config.js containing this:
```
module.exports = {
  parser: 'sugarss',
  plugins: {
    'postcss-url': {
      url: 'rebase',
    },
    'postcss-nested': {},
    'postcss-preset-env': {
      stage: 3,
    },
    autoprefixer: {},
    precss: {},
  },
};
```
As far as I can see e.g. 'postcss-preset-env' is working but sugarss is not (in rollup.config.js I am using just { postcss: true }). If you have any idea about what's wrong here - please let me know. I can even help fixing this because my team really needs this. Thanks

**Comment by kaisermann** [comment]
Good find! `svelte-preprocess` was only handling the `options.plugins`. I just released `v2.13.0` with support for the `parser`/`syntax` options.

**Comment by shamsartem** [comment]
Hey man. I really appreciate you work. Thank you so much!

**Comment by hcavalieri** [comment]
@shamsartem could you please walk us through how you made sugarss work with `svelte-preprocess`?

- Are you using inline styles or external files? If the latter, with which extension?
- How did you set your rollup/webpack/(other bundler) config?

I'm getting "unexpected identifier" whenever I write styles with the `sss` syntax 😔

**Comment by kaisermann** [comment]
@hcavalieri Thanks for the detailed feedback! Would you be able to provide a minimal reproducible example in a repo?

On another note, `svelte-preprocess` uses `postcss-load-config` behind the scenes, which accepts a bunch of other config file formats: https://www.npmjs.com/package/postcss-load-config#postcssrc
