### ISSUE TITLE
Can't get typescript to work with webpack

### ISSUE THREAD

**Issue by Zerowalker** [kaisermann/svelte-preprocess#49]
I simply can't get it to work, i got it setup like this:

> module: {
>     rules: [
>       {
>         test: /\.(html|svelte)$/,
>         exclude: /node_modules/,
>         use: {
>           loader: "svelte-loader",
>           options: {
>             emitCss: true,
>             hotReload: true,
>             preprocess: require("svelte-preprocess")({})
>           }
>         }
>       },
>       {
>         test: /\.css$/,
>         use: [
>           /**
>            * MiniCssExtractPlugin doesn't support HMR.
>            * For developing, use 'style-loader' instead.
>            * */
>           prod ? MiniCssExtractPlugin.loader : "style-loader",
>           "css-loader"
>         ]
>       }
>     ]
>   },

**Comment by MadOPcode** [comment]
Same here.
I've created a template to tinker with
https://github.com/MadOPcode/svelte-preprocess-template
Currently `npm run build:dev` spews lots of errors from typescript showing that typescript compiler tries to parse components' templates (HTML) for some reason.
The documentation mentions *auto preprocessing mode* which I guess is working only if you feed all the .svelte file's contents to it.
So the question is: does svelte-preprocess work in this auto preprocessing mode when used with svelte-loader?
And if it does then could @kaisermann or someone else provide a working template with webpack config or help getting my template into shape?

**Comment by kaisermann** [comment]
@MadOPcode `auto preprocessing mode` means using the default export from the `svelte-preprocess` module. It will automatically preprocess whatever language it sees on your `.svelte` files. If you configure your `preprocess` property on `svelte-loader` options with one of the [stand-alone processors](https://github.com/kaisermann/svelte-preprocess#standalone-processors), it won't process anything that wasn't defined there. 

I'll check your repo and provide an example on the `examples` directory when I have some free time

**Comment by kaisermann** [comment]
Hey! Sorry for taking so long to give you a response. I've been able to reproduce it and released a fix for that warning in version `v3.0.1` 😁 

Thanks!

**Comment by MadOPcode** [comment]
@kaisermann thanks for spending your time on this but I'm not sure what warning are you talking about. With `v3.0.2` the issue does not seem to be resolved. The `npm run build:dev` command from my repo still spews the same errors.
<details>
<summary>E.g.</summary>

```
> cross-env NODE_ENV=development webpack

src/components/App/App.svelte:1:2 - error TS2304: Cannot find name 'template'.

1 <template>
   ~~~~~~~~
src/components/App/App.svelte:2:4 - error TS2304: Cannot find name 'div'.

2   <div id="app">
     ~~~
src/components/App/App.svelte:2:8 - error TS1005: '>' expected.
```

</details>

**Comment by kaisermann** [comment]
@MadOPcode Strange 🤔 I've cloned your repo again, updated the package and ran `build:dev` and this is what I'm getting:

![image](https://user-images.githubusercontent.com/12702016/64193661-9477d700-ce53-11e9-93b3-09b9d187cc09.png)

(the warning can be fixed by changing the `Nested` import to `components/Nested/Nested.svelte`)

**Comment by MadOPcode** [comment]
@kaisermann what node version are you using? I'm currently on `v12.9.1` (was on `v12.3.1` when I created the repo).

**Comment by kaisermann** [comment]
Currently on `v12.9.0` (first line):

![image](https://user-images.githubusercontent.com/12702016/64280135-e3427100-cf26-11e9-83d4-0566b54d230c.png)
