### ISSUE TITLE
import scss in server.js

### ISSUE THREAD

**Issue by timeshift92** [kaisermann/svelte-preprocess#51]
import './assets/styles/index.scss';
not working

**Comment by kaisermann** [comment]
Hi! Have you configured both the `client` and `server` preprocess step? https://github.com/kaisermann/svelte-preprocess#with-sapper

**Comment by timeshift92** [comment]
Server step

**Comment by timeshift92** [comment]
![image](https://user-images.githubusercontent.com/13614530/61965393-824f8100-afe9-11e9-9857-f206ae397001.png)

Hello, I'm sorry my English is very bad, I put both on the client and on the server and did import on the server

![image](https://user-images.githubusercontent.com/13614530/61965470-ba56c400-afe9-11e9-84f8-3522e11605ab.png)

**Comment by kaisermann** [comment]
Oh, I see what's happening. You can't import css directly on the `server.js`. It must be inside a svelte template for `svelte-preprocess` to be able to see it.

**Comment by QuantumInformation** [comment]
Oh, so you can't put it in an import likes so:

index.scss
```
@import "~@material/top-app-bar/mdc-top-app-bar";
@import "~@material/icon-button/mdc-icon-button";```

and then in client.js:

import './index.scss'
?

**Comment by kaisermann** [comment]
@QuantumInformation `svelte-preprocess` only preprocesses your `.svelte` files or whatever files you import in them (via the `@import` i.e). If you wish to `import` your `scss` file on your `client.js` you can configure your bundler to support that kind of `import` (example: [rollup-plugin-scss](https://www.npmjs.com/package/rollup-plugin-scss) or [sass-loader](https://github.com/webpack-contrib/sass-loader))
