### ISSUE TITLE
@font-face import not work

### ISSUE THREAD

**Issue by timeshift92** [kaisermann/svelte-preprocess#52]
@font-face {
    font-family: Pompadur;
    src: url(fonts/pompadur.ttf);
}
not work with sapper

**Comment by kaisermann** [comment]
That's an issue with svelte itself https://github.com/sveltejs/svelte/issues/1324 and there's a PR to fix it https://github.com/sveltejs/svelte/pull/2995

**Comment by timeshift92** [comment]
Thanks
