### ISSUE TITLE
Vscode shows error with nested scss 

### ISSUE THREAD

**Issue by rgfx** [kaisermann/svelte-preprocess#57]
The problem is in vscode for sure, wondering if anyone has a solution. 

![image](https://user-images.githubusercontent.com/2388078/63219174-8d4d8b00-c129-11e9-9fb0-56260a125155.png)

**Comment by nickyhajal** [comment]
Also wondering about how to get VSCode to handle this better depending on the language being used

**Comment by kaisermann** [comment]
Hello! You need to create a `svelte.config.js` file on the project root so svelte-vscode know how to properly preprocess your files: https://github.com/kaisermann/svelte-preprocess#with-svelte-vs-code

**Comment by kaisermann** [comment]
I've added a FAQ section to the readme explaining this: https://github.com/kaisermann/svelte-preprocess#FAQ

**Comment by nickyhajal** [comment]
Thanks @kaisermann 

This seems to work well for scss, but I haven't been able to figure out how to configure `svelte.config.js` to show stylus correctly

![image](https://user-images.githubusercontent.com/1079625/63585288-1425bc00-c59f-11e9-9884-ff76ec7fa82d.png)

In `svelte.config.js` I have:

```
const sveltePreprocess = require('svelte-preprocess');
module.exports = {
  preprocess: sveltePreprocess({
    stylus: {
      paths: ['node_modules'],
    },
  }),
};
```

**Comment by nickyhajal** [comment]
Thanks, great point!

**Comment by rwwagner90** [comment]
I'm getting a bunch of issues like this, not using VSCode at all. Just trying to preprocess scss in svelte and I get `Colon is expected` and other issues with `Identifier expected`. It seems this package does not work with nested rules.
