### ISSUE TITLE
Global Variables?

### ISSUE THREAD

**Issue by nickyhajal** [kaisermann/svelte-preprocess#58]
Is there a way to define variables in a global style block (scss or stylus) that will then be accessible to components?

I'm trying the following in `App.svelte` but the components don't seem to see the variables:

```
<style lang="scss" global>
  $black: #000;
  $red: #c10;
</style>
```

The error I receive is:

`(plugin svelte) Error: Undefined variable.`

Thank you!

**Comment by nickyhajal** [comment]
Thanks for the quick reply! That makes sense 👍

**Comment by fanckush** [comment]
@kaisermann is the only way to get this to possibly work to open an issue on Svelte's repo?
This is such an important thing to have and others like Vue have it almost out of the box..

**Comment by kaisermann** [comment]
@fanckush Posted another way of doing this on https://github.com/sveltejs/sapper/issues/474
