### ISSUE TITLE
Can I use mixins?

### ISSUE THREAD

**Issue by rgfx** [kaisermann/svelte-preprocess#61]
Using sveltePreprocess shouldn't I be able to do something like this? Gives `no mixin named bp.`

```
  @mixin bp($point) {
    @if $point==full {
      @media (min-width: 1366px) {
        @content;
      }
    } @else if $point==medium {
      @media (min-width: 1000px) {
        @content;
      }
    } @else if $point==small {
      @media (min-width: 550px) {
        @content;
      }
    }
  }

  @include bp(medium){
    background:green,
  }
```

Maybe my setup is wrong.

**Comment by rgfx** [comment]
@kaisermann so I have to add  @import "./style/mixins.scss"; to every style block I want to add the mixin too? 

What would you do if you wanted to add a style to every page, like a` @font` or something?

stick in the `_layout`?

Right now when I change a style in `global.css` nothing happens. 

Can you please look at my rollup and if I did something wrong? 

https://github.com/rgfx/svelte-scss-setup

Also, can I make scss file like this

```
@charset 'UTF-8';
@import "normalize";
@import "mixins";
@import "base";
```

**Comment by fanckush** [comment]
@rgfx check #58 it seems to be a limitation from Svelte.
So yes you have to import your the file containing the mixin _every_ time you need it in all your components
