### ISSUE TITLE
error  Identifier is expected  ParseError

### ISSUE THREAD

**Issue by rwwagner90** [kaisermann/svelte-preprocess#62]
I keep getting `error  Identifier is expected  ParseError` whenever I use `&` in SCSS. Any ideas how to fix this?

**Comment by kaisermann** [comment]
@rwwagner90 Would you be able to provide a minimal reproducible example? A repo would be great

**Comment by rwwagner90** [comment]
@kaisermann I switched to using vanilla CSS, as I wasn't sure what was going on here. I will try to get an example.

**Comment by rwwagner90** [comment]
@kaisermann I added it back and got things working, kind of. I am now seeing some issues when trying to run tests via jest, with the same error:

```
    ParseError: Identifier is expected

      at error$1 (node_modules/svelte/src/compiler/utils/error.ts:25:16)
      at Parser$2.error (node_modules/svelte/src/compiler/parse/index.ts:93:3)
      at Object.read_style [as read] (node_modules/svelte/src/compiler/parse/read/style.ts:20:11)
      at tag (node_modules/svelte/src/compiler/parse/state/tag.ts:221:27)
      at new Parser$2 (node_modules/svelte/src/compiler/parse/index.ts:45:12)
      at parse$1 (node_modules/svelte/src/compiler/parse/index.ts:208:17)
      at Object.parse [as compile] (node_modules/svelte/src/compiler/compile/index.ts:68:14)
      at Object.process (node_modules/jest-transform-svelte/index.js:21:26)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:453:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:523:40)
```

**Comment by rwwagner90** [comment]
@kaisermann the failures can be reproduced by pulling down https://github.com/shipshapecode/shepherd/pull/551 and running `yarn test`

**Comment by kaisermann** [comment]
Thanks @rwwagner90. I'll check it out when I get some free time 😬

**Comment by rwwagner90** [comment]
Thanks @kaisermann! If you know of any example apps using rollup, babel, svelte, svelte-preprocess, and testing with test, please let me know! I think it's something just isn't running right with jest, even though I think I have specified the transforms.

**Comment by Chris56974** [comment]
I think I might have the same issue (I could be mistaken). Here is a [minimal sapper repository](https://github.com/Chris56974/sapper-rollup-scss-typescript). When I export using ES6 modules I get the same error as OP. But when I export using commonJS modules I get the error "unrecognized option 'markup'".

**Comment by kaisermann** [comment]
@Chris56974 I'm not close to a keyboard right now, but could you try changing your svelte.config.js to syntax to commonjs (`module.exports` instead of `export default`)? I'm not sure this would fix your issue, but it's a start 😬

**Comment by Chris56974** [comment]
Ah, I was doing something silly. When I tried commonjs syntax I did...
```js
const sveltePreprocess = require('svelte-preprocess');

const preprocess = sveltePreprocess({
  postcss: {
    plugins: [require('autoprefixer')]
  },
  scss: true
});

module.exports = preprocess;
```
Which gave me the 'Unrecognized option 'markup'' error. Instead, I should have done...
```js
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: sveltePreprocess({
    postcss: {
      plugins: [require('autoprefixer')]
    },
    scss: true
  })
};
```
Thanks for helping me out @kaisermann, everything is working just fine for me now.

**Comment by kaisermann** [comment]
Haaa, I didn't notice that too 👀. Great that's working now 🎉
