### ISSUE TITLE
Imported .ts files are not recognized

### ISSUE THREAD

**Issue by LooneyDude** [kaisermann/svelte-preprocess#63]
Hello,

nice plugin that works mostly perfect. But have a problem with external .ts files.

Sorry, if this is the wrong place, but maybe you can help me.

I defined a class in an external .ts file and want to import it in my svelte script file. The script is embedded as external file:

App.svelte:
`<script src="script.ts" lang="typescript"></script>`

script.ts:
```
import {CardItemAnimal} from "../models/CardItem";
let animal = new CardItemAnimal();
```

CardItem.ts:
```
export interface CardItem {
    id: string;
    name: string;
    image: string;
}

export  class CardItemPerson implements CardItem{
    private _type: string = 'person';

    id: string;
    name: string;
    image: string;

    public get type(): string {
        return this._type;
    };
}
```

As result I get an error:

```
[!] Error: Could not resolve '../models/CardItem' from src/App/App.svelte
Error: Could not resolve '../models/CardItem' from src/App/App.svelte
    at error (/Users/mjay/Sites/wolken.fun/petz.fun/click-dummy/svelte/dummy/node_modules/rollup/dist/rollup.js:9419:30)
    at ModuleLoader.handleMissingImports (/Users/mjay/Sites/wolken.fun/petz.fun/click-dummy/svelte/dummy/node_modules/rollup/dist/rollup.js:16467:17)
    at ModuleLoader.<anonymous> (/Users/mjay/Sites/wolken.fun/petz.fun/click-dummy/svelte/dummy/node_modules/rollup/dist/rollup.js:16518:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mjay/Sites/wolken.fun/petz.fun/click-dummy/svelte/dummy/node_modules/rollup/dist/rollup.js:40:28)
```

It's the same when I changed CardItemPerson to a default export. I don't know, where to start search for an error. Your plugin, rollup, svelte, tsconfig.json ...

Have you any idea?

**Comment by LooneyDude** [comment]
I made a repo to reproduce this problem: https://github.com/LooneyDude/svelte-ts-scss-starter

**Comment by kaisermann** [comment]
@LooneyDude Hi! Sorry for taking so long to give you an answer. Thanks for the reproducible example 😁 

It seems you're getting that error because after being preprocessed, rollup tries to resolve that `import` and it doesn't find anything with the `/cardItem` name. I think the solution here would be to make rollup understand typescript imports by installing `rollup-plugin-typescript` and `tslib` 😁

**Comment by LooneyDude** [comment]
@kaisermann  **thanks for your support**! I wasn't sure if the issues are the right place for my question, so I'm glad that you'r helping, even if it took a little longer. :) 

I implemented your suggestions and now it works great. See the changes in my repo:  https://github.com/LooneyDude/svelte-ts-scss-starter

I noticed one small thing: 
All compiled correctly, but in the main.ts, vs-code reported that it could not resolve the module (`import App from './App/App.svelte';`). I installed `@pyoner/svelte-types' and then referenced it in the tsconfig.json fixed the bug. Or is there is an other/better solution?

**Comment by kaisermann** [comment]
@LooneyDude No problem 😁! 

And for that case, you'd need to at least `declare module '*.svelte'` in some `.d.ts` file so `typescript` can resolve it as a module. That`s exactly what `@pyoner/svelte-types` [does](https://github.com/pyoner/svelte-typescript/blob/master/packages/types/types/svelte/svelte.d.ts#L1).
