### ISSUE TITLE
External script sourcemap

### ISSUE THREAD

**Issue by jvmccarthy** [kaisermann/svelte-preprocess#7]
Thank you for adding support for external files. I'm probably in the minority, but it's also the structure I prefer and something I really like about vue-loader. It's a lot easier for IDEs to recognize individual files.

However, I'm hitting a roadblock with source maps. I've looked at the source that resolves external files. Here's my setup: I'm using pug and scss (which doesn't matter in this case). My component files have a structure like this,

```html
<template src='./template.pug' lang='pug'></template>
<style src='./style.scss' lang='scss'></style>
<script src='./script.js'></script>
```

When I try to minify my code and put a breakpoint in `script.js`, I just end up back at this file instead of the script file. 

I tried looking into how vue-loader does this, since they do something similar. However, it looks like they just convert these references to `require` calls and allow webpack to resolve and add the source map.

I then tried to find inspiration in rollup-plugin-commonjs, since it allows for resolving `require` statements (see [transform.js](https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js)). It uses the utility [magic-string](https://github.com/Rich-Harris/magic-string), which seems like it might help in this case.

**Comment by jvmccarthy** [comment]
Looks like preprocess maps aren't currently being used. From svelte's readme,

> Note that sourcemaps are currently discarded, but will be used in future versions of Svelte.

So there's some upstream work to be done here. Nevertheless, I'm still finding it very hard to find a simple recipe or example of generating a source map for importing a file. I've poked around a number of places. Looking at the source-maps repo, it seems like this should be possible with [`SourceNode`](https://github.com/mozilla/source-map#sourcenode). I was also looking at [`test-source-map-generator.js`](https://github.com/mozilla/source-map/blob/ddaac7f00a67aefbf184bae16cb90b30ddc84a67/test/test-source-map-generator.js#L286) or [`test-source-node.js`](https://github.com/mozilla/source-map/blob/master/test/test-source-node.js) for inspiration.

**Comment by kaisermann** [comment]
I still think this could be useful, but there's no use for sourcemaps in `svelte` for the time being. This issue will be kept closed until `svelte` actually does something with sourcemaps.
