### ISSUE TITLE
TypeScript preprocessing of export and $:

### ISSUE THREAD

**Issue by mvolkmann** [kaisermann/svelte-preprocess#73]
It seems that TypeScript doesn't know what do with export statements for props or $: labels for reactive statements. Is there a way to get it to properly handle those?

**Comment by mvolkmann** [comment]
I looked into this a bit more. Use `$:` is working for me now. However, `export` for props is not working. For example, this does not work:

```html
<script lang="typescript">
  export const title: string = 'untitled';
</script>

<div>{title}</div>
```

I get the error "ReferenceError: title is not defined".

**Comment by kaisermann** [comment]
Hi @mvolkmann, can you provide a reproducible repo example? I've just tested this on the `examples/sapper-rollup` project and it works as expected.

**Comment by mvolkmann** [comment]
Here is a GitHub repo with a simple example that demonstrates the issue:
git@github.com:mvolkmann/svelte-typescript.git
Try to run this app and see the messages.

**Comment by kaisermann** [comment]
You don't have a `tsconfig.json` in that repo, so the typescript compiler is transpiling your code to `es3` by default, which svelte doesn't like very much (it works only with es6 import/export syntax).

You can just add a `tsconfig.json` with `compilerOptions.target` set to something higher than `es5:

```js
{
	"compilerOptions": {
		"target": "es6"
	}
}

```

**Comment by mvolkmann** [comment]
Thanks! That worked! Now I just need to get VS Code to flag TypeScript errors. Do you have any tips on how to configure that?

**Comment by kaisermann** [comment]
What do you mean by flagging the typescript errors? Vscode isn't showing them on the UI?

**Comment by mvolkmann** [comment]
For whatever reason, my VS Code is no longer flagging TypeScript errors in this example code. I'll close this.

**Comment by mvolkmann** [comment]
Ugh! It's back.

**Comment by mvolkmann** [comment]
@kaisermann Do you see anything wrong with this?
https://github.com/mvolkmann/svelte-typescript/blob/master/svelte.config.js

Here is a screenshot showing what VS Code is flagging.
![Screen Shot 2019-10-26 at 1 02 30 PM](https://user-images.githubusercontent.com/79312/67623949-ed7b4000-f7f0-11e9-89c9-9d974bb189ed.png)
It says "Unexpected token svelte(parse-error)"

**Comment by mvolkmann** [comment]
Restarting VS Code seems to have fixed this.
