### ISSUE TITLE
Error: Cannot find module './typings'

### ISSUE THREAD

**Issue by evdama** [kaisermann/svelte-preprocess#79]
I just upgraded from `svelte-preprocess` 3.1.2. to `"svelte-preprocess": "^3.2.0-alpha.1"` which breaks the build with following error on the console:

```sh
> Cannot find module './typings'
Require stack:
- /Users/sa/0/edm/node_modules/svelte-preprocess/dist/index.js
- /Users/sa/0/edm/rollup.config.js
- /Users/sa/0/edm/node_modules/sapper/dist/core.js
- /Users/sa/0/edm/node_modules/sapper/dist/build.js
- /Users/sa/0/edm/node_modules/sapper/dist/cli.js
- /Users/sa/0/edm/node_modules/sapper/sapper
Error: Cannot find module './typings'
```

Without any change to anything else in my sapper project, just downgrading to 3.1.2 makes all work again.

**Comment by rosano** [comment]
Yes I was not able to deploy my site using the latest version but downgrading to 3.1.2 works. I could not find `typings` in the source 🤔.

**Comment by kaisermann** [comment]
Hey 😁 Sorry, that version wasn't supposed to be installed just yet... Can you please rollback for now?

**Comment by evdama** [comment]
roger that :)
closing...
