### ISSUE TITLE
Imported CSS files do not update on save

### ISSUE THREAD

**Issue by limitlessloop** [kaisermann/svelte-preprocess#8]
You might be already aware of this, but when using `postcss-import` and making changes to files which are imported they do not update on the server after they are saved or after reloading the browser.

```html
<!-- component.html -->
<div class="test"></div>
<style>
    @import `colors.css`; /* .test { color: red } */
    .test {
       color: blue;
    }
</style>
```

```js
// webpack.config.js
//...
const preprocess = require('svelte-preprocess');
//...
const options = {
    transformers: {
        postcss: {
            plugins: [
                require('postcss-import'),
                require('autoprefixer')({ browsers: 'last 2 versions' })
            ]
       }
    }
}
//...
options: {
    css: true,
    generate: "ssr",
    dev,
    preprocess: preprocess(options)
}
```
I'm not sure if this is related to `svelte-preprocess`, `svelte-loader`, or `postcss-import`.

Any thoughts?

**Comment by kaisermann** [comment]
Right now that's not possible because we can't pass external dependencies within the `preprocess` step. However, there's an issue exactly for that on `svelte` https://github.com/sveltejs/svelte/issues/1720 😁

**Comment by kaisermann** [comment]
Implemented on v2.5.0 by #16. We're just waiting `svelte-loader` to support it as well

**Comment by mindthetic** [comment]
This will be a very welcome addition. Thanks

**Comment by kaisermann** [comment]
@mindthetic Oops, my bad. `v2.5.0` will only watch for the direct external files (the ones you import with `src="./.../..."`). But it's a start for watching imported files as well

**Comment by mindthetic** [comment]
No worries. At least it could be a work around for now.

**Comment by mindthetic** [comment]
I thought maybe I could use this as a work around but I'm not sure I understand how to use it the way you mentioned. Do you mean you would be able to do...

```my-component.html
<style src="./style.css"></style>
```
and the browser will reload when `styles.css` is updated?

**Comment by kaisermann** [comment]
@mindthetic Yes! But we have to wait for https://github.com/sveltejs/svelte-loader/pull/75 first :sob:

**Comment by mindthetic** [comment]
Ah I see. Cool. Thanks for clarifying.

**Comment by eBaeza** [comment]
What happens whit this??? I saw that the [sveltejs/svelte-loader#75](https://github.com/sveltejs/svelte-loader/pull/75) it´s already merged and released

**Comment by kaisermann** [comment]
Just added support to watch `@imported` with `postcss-import`/`postcss-easy-import` on v2.7.0 🎉
