### ISSUE TITLE
Pug error when using '&&'

### ISSUE THREAD

**Issue by kapilpipaliya** [kaisermann/svelte-preprocess#82]
i have this line in pug template:
`a(href="{m.children && m.children.length ? null : m.path}" )`
but it gives error: `<a href="{c.children &amp;&amp; c.children.length ? null : c.path}"` at &&.

**Comment by kaisermann** [comment]
@kapilpipaliya That's happening because `pug` is encoding those `&&` into html entities. Instead of `=` use the `!=` operator: `a(href!=".... && ...")` and it should work! 

I should probably make this clearer somewhere on the readme. Thanks for the alert!

**Comment by kaisermann** [comment]
Added it to the readme: https://github.com/kaisermann/svelte-preprocess/#element-attributes

Thanks for the info 😁
