### ISSUE TITLE
Feat: add support for markdown markup

### ISSUE THREAD

**Issue by kaisermann** [kaisermann/svelte-preprocess#83]
Title pretty self explanatory. Would be a nice addition to have a basic markdown processor for components markup.

**Comment by kaisermann** [comment]
Nah, having took a better look into https://github.com/pngwn/MDsveX, I no longer think that a very basic markdown preprocessor would be that great of an addition. If someone wants a nice `markdown` preprocessor, just use `mdsvex` 😁

**Comment by khaki32** [comment]
Is there any chance of this happening

I'd prefer a solution using svelte-preprocess, because in my experience mdsvex is buggy. It has bad support for SvelteKit and TailwindCSS.
