### ISSUE TITLE
pug nested template not work.

### ISSUE THREAD

**Issue by kapilpipaliya** [kaisermann/svelte-preprocess#85]
```
<template lang="pug">
    <template src='./_new.pug'></template>
</template>

```
This not gives error, but `_new.pug` not rendered.

**Comment by kaisermann** [comment]
Hey 😁! Is that internal `<template>` a pug feature? Any markup code inside your outer `<template>` must be in the language you defined on the `lang` or `type` attributes

**Comment by kapilpipaliya** [comment]
no its not a pug feature.
I tried [https://pugjs.org/language/includes.html](https://pugjs.org/language/includes.html) and it works. thanks!
