### ISSUE TITLE
Breaks cdn delivered js files

### ISSUE THREAD

**Issue by antony** [kaisermann/svelte-preprocess#9]
I've installed this in my project, but unfortunately it looks like it tries to look for external JS files on the local filesystem:

```html
<script src="//maps.googleapis.com/maps/api/js?key=xxx&libraries=places"></script>
```

For example, causes the error:

```bash
Error: Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ENOENT: no such file or directory, open '/home/ant/Projects/xxx/src/routes/https:/maps.googleapis.com/maps/api/js?ke'
    at Object.fs.openSync (fs.js:660:18)
    at fs.readFileSync (fs.js:565:33)
    at exports.getSrcContent (/home/ant/Projects/xxx/node_modules/svelte-preprocess/src/utils.js:46:3)
```

**Comment by kaisermann** [comment]
Is there a particular reason for trying to load a remote js instead of your component `<script>`? Or are you trying to use multiple `<script>` tags?

**Comment by antony** [comment]
Google force you to load their maps API JS from their servers. You're not allowed to host it locally.

**Comment by antony** [comment]
(also, same with MailChimp)

**Comment by kaisermann** [comment]
But since you can only have one single `<script>` tag per component, wouldn't it be better to load it on your (real) `html` template? Or dynamically?

Something like:

```js
const script = document.createElement('script');

script.type = 'text/javascript';
script.src = '/maps.googleapis.com/maps/api/js?key=xxx&libraries=places';

document.getElementsByTagName('head')[0].appendChild(script);
```
