### ISSUE TITLE
cant import svelte component in typescript.

### ISSUE THREAD

**Issue by kapilpipaliya** [kaisermann/svelte-preprocess#91]
I tried to import a javascript file.
```
<script lang="typescript">
    import {Table, Th, Tr, Pagination} from '../../index.js'
</script>
```
index.js:
```
import Table from '../routes/_components/STable.svelte'
import Th from '../routes/_components/STh.svelte'
import Tr from '../routes/_components/STr.svelte'

export {
  Table, Th, Tr
}
```
but it gives error: 
`'Table' is not defined,  'Th' is not defined etc`

**Comment by kapilpipaliya** [comment]
```
<script lang="typescript">
    import Sidebar from '../_components/layout/Sidebar.svelte'
</script>
```
gives error:
`'Sidebar' is not defined`

**Comment by kapilpipaliya** [comment]
This solves the problem. Thanks @cortopy 
```
<script lang="typescript">
    import {Table, Th, Tr} from 'index.ts'
    console.log(Table, Th, Tr)
</script>
```

**Comment by kapilpipaliya** [comment]
but i cant use types on `index.ts` file:
```
function greeter(person: string) {
  return "Hello, " + person;
}
```
gives error.

**Comment by kaisermann** [comment]
Hey @kapilpipaliya 👋Can you share a sample project ?

**Comment by kapilpipaliya** [comment]
https://github.com/kapilpipaliya/sapper_typescript_error

**Comment by kaisermann** [comment]
That example seems to be related to #92 (helped solving that issue, thanks!). Can you provide one for this issue?

**Comment by kapilpipaliya** [comment]
change index.ts file:
```

function greeter(person: string) {
  return "Hello, " + person;
}
```
gives error.

**Comment by kaisermann** [comment]
Ahh, I see. That's happening because you're importing it via a `import ... from './_form.ts'`. Your bundle, in this case `webpack`, should be configured to handle `typescript` imports (via `ts-loader` i.e). `svelte-preprocess` only adds support for using typescript inside a component's `<script>` tag.

**Comment by kaisermann** [comment]
Ahh, I see. That's happening because you're importing it via a import ... from './_form.ts'. Your bundler, in this case webpack, should be configured to handle typescript imports (via ts-loader i.e). svelte-preprocess only adds support for using typescript inside a component's <script> tag.

- You need to install `ts-loader` and add it to the _client_ and _server_ `rules`
- Create a `tsconfig.json` and add `svelte` to the `types` array:

```
{
	"compilerOptions": {
		"types": ["svelte"],
	}
}
```

And it should start working.

**Comment by kapilpipaliya** [comment]
Thanks, 

- I install `ts-loader` and added it to client and server `rules`.
- I configured tsconfig.json file as you said.
Now typescript file with type works. Thank you so much.

but I still Have to write this for component imports:
```
import {Table, Th, Tr, Pagination, ShowError, Add, TdEdit, TdDelete} from 'index.ts'
(ShowError, Add, Table, Th, Tr, TdEdit, TdDelete, Pagination);
```
if i not use above line it gives error: `Uncaught (in promise) ReferenceError: ShowError is not defined`

**Comment by kaisermann** [comment]
That's fixed on `v3.2.2`. Thanks for the feedback! 🙏

**Comment by kapilpipaliya** [comment]
Thank you. you are great!

**Comment by joelmukuthu** [comment]
Hi @kaisermann, thank you so much for your work and support on this project! :heart:

> Create a tsconfig.json and add svelte to the types array

I'm sorry to ask this here but what exactly does adding `["svelte"]` to `"types"` in a `tsconfig.json` do? I had a similar problem and found this issue and that comment helped me fix it. I don't have any `@types/svelte` module in `node_modules/` so I'm just a bit confused as to why it works? :)

**Comment by fhassis** [comment]
Hi @kaisermann, I have the same issue of not being able to import from .ts files inside <script lang="typescript"> tag. I am using Rollup. I can now use .ts files after installing "@rollup/plugin-typescript". Have you seen this behavior before?

**Comment by programmerinprogress** [comment]
> Hi @kaisermann, I have the same issue of not being able to import from .ts files inside <script lang="typescript"> tag. I am using Rollup. I can now use .ts files after installing "@rollup/plugin-typescript". Have you seen this behavior before?

Same, would really like to see if there's a solution to this. 

The issue (from what i've read) seems to be when you're importing svelte 'modules' (svelte code that is wrapped in <script context="module" ... tags.

I can only get the project to work by changing the .ts file back to a .js file.

**Comment by programmerinprogress** [comment]
> > Hi @kaisermann, I have the same issue of not being able to import from .ts files inside <script lang="typescript"> tag. I am using Rollup. I can now use .ts files after installing "@rollup/plugin-typescript". Have you seen this behavior before?
> 
> Same, would really like to see if there's a solution to this.
> 
> The issue (from what i've read) seems to be when you're importing svelte 'modules' (svelte code that is wrapped in <script context="module" ... tags.
> 
> I can only get the project to work by changing the .ts file back to a .js file.

I found a solution for my particular issue: 

1. set up your .tsconfig , add a "types" property to your compiler options like this:
`"typeRoots": ["./node_modules/@types", "./src/@types"],`

2. add a new folder called `@types` at the path you just specified

3. add a `main.d.ts` file to the folder you just created

4. inside the `main.d.ts` add `declare module 'name-of-node-module-you-were-trying-to-import';`

That fixed the errors in vscode for me and fixed the error when I ran the code in dev mode (I use rollup and the rollup-typescript-plugin)
