### ISSUE TITLE
pug Shorthand attribute not working.

### ISSUE THREAD

**Issue by kapilpipaliya** [kaisermann/svelte-preprocess#92]
in pug template this works:
`Table(data='{$data}' currentPage='{currentPage}' selectedClass='secondary')`
this not work:
`Table({$data} {currentPage} selectedClass='secondary')`
I can't write Shorthand, for when name and value match.
Thank you.

**Comment by kapilpipaliya** [comment]
another issue:
I have:
```
<script>
    import {CRUD} from './_form.js'
    const c = new CRUD();
    const er = c.er;
</script>
```
This not working on pug templte:
`ShowError(er='{c.$er}')`
but this works:
`ShowError(er='{$er}')`

**Comment by kaisermann** [comment]
Same thing as #91, can you share a small reproducible project?

**Comment by kaisermann** [comment]
That's actually because the `$` store syntax is only supported for top-level variables, not for object properties. If you want to access your store in that way, you should access it by `c.er`, without the dollar sign and you'd have to do some other stuff to get its value.
