### ISSUE TITLE
Typescript import not exporting properly

### ISSUE THREAD

**Issue by farhan2106** [kaisermann/svelte-preprocess#94]
**Describe the bug**

`link` variable is not exported properly.

```
<script lang="typescript">
  import { link } from "svelte-routing";
</script>

<template>
  <a href="/" use:link class="navbar-item">
    Home
  </a>
  <a href="/about" use:link class="navbar-item">
    About Us
  </a>
</template>
```

![Screenshot from 2019-10-31 17-20-59](https://user-images.githubusercontent.com/897173/67934465-eabe8780-fc02-11e9-99be-889b813e9dd6.png)

Mt TSconfig
[tsconfig.txt](https://github.com/kaisermann/svelte-preprocess/files/3793025/tsconfig.txt)

**Comment by farhan2106** [comment]
But, when I do the following, it works.
```
<script lang="typescript">
  import { link } from "svelte-routing";

  let r = link
</script>

<template>
  <a href="/" use:r class="navbar-item">
    Home
  </a>
  <a href="/about" use:link class="navbar-item">
    About Us
  </a>
</template>
```

**Comment by farhan2106** [comment]
Aaaaa; Figured out why, typescript removes unused variable. Since `link` variable is not used in the `script` tag, the `link` variable will be removed by TS. Haha

```import { link } from "svelte-routing";link;``` works.

**Comment by kaisermann** [comment]
@farhan2106 which version of `svelte-preprocess` were you using? This is supposed to be fixed on `v3.2.1`

**Comment by farhan2106** [comment]
@kaisermann I am using `3.2.1`. Not sure if there is a special settings in `tsconfig` that doesn't automatically unused variables

**Comment by farhan2106** [comment]
Basically, I have to create a dummy reference to the variable `link` so that it doesn't get removed by typescript.

```
<script lang="typescript">
  import { link } from "svelte-routing";

  // dummy reference
  link;
</script>


<template>
  <a href="/" use:link class="navbar-item">
    Home
  </a>
  <a href="/about" use:link class="navbar-item">
    About Us
  </a>
</template>
```

**Comment by kaisermann** [comment]
@farhan2106 hum... 🤔 you shouldn't be needing to create that dummy reference. Would you be abble to share a reproducible repo?

**Comment by kaisermann** [comment]
Can you test this template? I just cloned the `sveltejs/template`, added `svelte-preprocess`, `typescript` and tried the above code without the dummy reference and it seems to bbe working as expected. 

[template.zip](https://github.com/kaisermann/svelte-preprocess/files/3795480/template.zip)

**Comment by farhan2106** [comment]
You're right. It is working. Maybe I used an older version of svelte-process.

Thanks man. Awesome work with this module. :)

**Comment by dkzlv** [comment]
For those of you who find this issue wondering why it doesn't work now, go ahead and try this trick:

```typescript
import type { Interface } from './types.ts'
```
Took me a while to get here but it works!
