### ISSUE TITLE
Commented tags are being processed

### ISSUE THREAD

**Issue by nitro52** [kaisermann/svelte-preprocess#96]
**Describe the bug**
I've noticed this a couple of times but i am currently trying to debug an issue with my styles not loading. 

I commented out the style tag but still got the same build error. I removed the commented line and the build works

**To Reproduce**
**Example 1**

1. Add the following sass script tag

```
<style type="text/scss">
     button {
         color: $something
     }
</style>
```
It should cause a build error because the `$something` variable does not exist. Comment the block 

```
<!--<style type="text/scss">
     button {
         color: $something
     }
</style>-->
```
You still get the build error. now add a css comment on the line using the `$something` variable
```
<!--<style type="text/scss">
     button {
         //color: $something
     }
</style>-->
```
No more build error. 

**Example 2**
load a separate sass file that contains the same build error. 
```
<style src="button.scss"></style>
```
Comment the style tag
```
<!--<style src="button.scss"></style>-->
```
still get the error. Remove the line fixes it. 

**Example 3**
Using line comments instead of block breaks it even more because it adds invalid sass to the lines being processed
```
<!--<style type="text/scss">-->
<!--     button {-->
<!--         color: $something-->
<!--     }-->
<!--</style>-->

```
**Expected behavior**
Html comments should not be ignored in valid html 

**Information about your project:**

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
Windows 10
- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)
3.2.5
- Whether your project uses Webpack or Rollup
Webpack

**Comment by kaisermann** [comment]
Hey @nitro52! This is actually a limitation of how svelte gets the `script` and `style` tags content. It uses a simple [`regexp`](https://github.com/sveltejs/svelte/blob/master/src/compiler/preprocess/index.ts#L113) that searches blindly, without information about the tag surroundings, for the tag and what's inside it. 

While searching for `<style*>*</style>`, `<!--<style>foo</style>-->` matches.

**Comment by nitro52** [comment]
Ah that explains, What is the execution order then? does svelete-loader run first to get each section then hand it off to the svelte-preprocessor?

**Comment by kaisermann** [comment]
The order is `svelte-loader` > `svelte.compile` > `svelte-preprocess`.

**Comment by nitro52** [comment]
The name svelte-preprocess makes it sound like it comes before compile.

**Comment by kaisermann** [comment]
Oh, sorry, my mistake hahaha. It's executed before the actual compilation, but it's the compiler who calls it.
