### ISSUE TITLE
Webpack alias not working with external scss file

### ISSUE THREAD

**Issue by nitro52** [kaisermann/svelte-preprocess#97]
**Describe the bug**
I'm not sure if this is a bug or a webpack config issue but when i try to import an external scss file using the src internal imports using webpack aliases do not work. 

**To Reproduce**

For example i have
```
<style src="button.scss"></style>
```
Which has a dependancy on a webpack alias 
```
@import "~@styles/default-theme/variables.scss";
```
but i get the error 
```
ERROR in ./src/common/button/Button.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: File to import not found or unreadable: ~@styles/default-theme/variables.scss.
```
However the build works if i use the alias imports within a style tag
```
<style>
    @import "~@styles/default-theme/variables.scss";
    @import "button.scss";
</style>
```
The problem i have with this method is my Styles don't work in Storybook but thats probably a config issue. 

**Expected behavior**
Webpack aliases work as intended. 

**Webpack Config**
<details>
  <summary>wepack.common.js</summary>

```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { CheckerPlugin } = require('awesome-typescript-loader');
const CopyPlugin = require('copy-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const path = require('path');

module.exports = {
	entry: {
		bundle: ['./src/main.ts', './src/styles/default-theme/all.scss']
	},
	resolve: {
		alias: {
			svelte: path.resolve('node_modules', 'svelte'),
			'@src': path.resolve(__dirname, 'src/'),
			'@styles': path.resolve(__dirname, 'src/styles/'),
			'@common': path.resolve(__dirname, 'src/common/'),
		},
		extensions: ['.mjs', '.ts', '.tsx', '.js', '.svelte', 'scss', 'css'],
		mainFields: ['svelte', 'browser', 'module', 'main'],
		modules: [path.resolve(__dirname, 'src'), 'node_modules']
	},
	output: {
		path: path.resolve(__dirname, 'build'),
		filename: '[name].js',
		chunkFilename: '[name].[id].js'
	},
	module: {
		rules: [
			{
				test: /\.(ts|tsx)$/,
				use: [{ loader: require.resolve('awesome-typescript-loader') }],
			},
			{
				test: /\.svelte$/,
				use: {
					loader: 'svelte-loader',
					options: {
						emitCss: true,
						hotReload: true,
						preprocess: require('svelte-preprocess')({ /* options */ })
					}
				}
			},
			{
				test: /.(png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$/,
				loader: 'url-loader?limit=10000',
			},
			/*Style rules are customised in separate dev/prod configs*/
		]
	},
	plugins: [
		new CleanWebpackPlugin(),
		new MiniCssExtractPlugin({
			filename: '[name].css'
		}),
		new CheckerPlugin(),
        new CopyPlugin([
            { from: 'public'},
			{ from: 'node_modules/@fortawesome/fontawesome-pro/webfonts', to: 'fonts'},
			{
				context: 'node_modules/@webcomponents/webcomponentsjs',
				from: '**/*.js',
				to: 'webcomponents'
			}
        ])
	]
};

```
</details>

<details>
  <summary>wepack.dev.js</summary>

```
const merge = require('webpack-merge');
const common = require('./webpack.common.js');
/**
 merge.smart replaces matches
 You can debug the output using
    console.dir(config, { depth: null });
 ref: https://github.com/survivejs/webpack-merge
 */
const config = merge.smart(common, {
    mode: 'development',
    devtool: 'inline-source-map',
    module: {
        rules: [
            {
                test: /\.(scss|sass|css)$/,
                use: [
                    /**
                     * MiniCssExtractPlugin doesn't support HMR.
                     * For developing, use 'style-loader' instead.
                     * */
                    'style-loader',
                    { loader: 'css-loader', options: { sourceMap: true } },
                    'sass-loader'
                ]
            }
        ]
    },
    devServer: {
        contentBase: './build',
        port: 4000
    },
});

console.dir(config, {depth: null});
module.exports = config;

```

</details>

**Information about your project:**
- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
Windows 10
- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)
3.2.5
- Whether your project uses Webpack or Rollup
Webpack
**Additional context**
Configured to use Typescript & Sass

**Comment by kaisermann** [comment]
`sass-loader` is able to know your webpack aliases because it has access to the webpack config context, because it's a loader. `svelte-preprocess` is executed in a total different manner, so it's not possible to automatically get your webpack aliases. 

This issue here is similar: https://github.com/kristerkari/react-native-sass-transformer/issues/19

I think it's outside of the scope of this module to provide out-of-the-box support for scss aliases, but I'm open to discuss it 😁

**Comment by kaisermann** [comment]
After taking a quick look at `scss` JS API docs,  here's a very simple importer which adds support for aliases: 

```js
const scssAliases = aliases => {
	return (url, prev, done) => {
		for (const [alias, aliasPath] of Object.entries(aliases)) {
			if (url.indexOf(alias) === 0) {
				console.log(url.replace(alias, aliasPath));
				return {
					file: url.replace(alias, aliasPath),
				};
			}
		}
		return url;
	};
};
```

And you would use it more or less like this:

```js
require('svelte-preprocess')({
		scss: {
			importer: [
				scssAliases({
					'@src': process.cwd() + '/src',
				}),
			],
		},
	}),
```

**Comment by nitro52** [comment]
Thanks, that helped me to sort it out. I didn't realise the sass property could be a sass options object. That helped me to mostly get aliases working ok my template https://github.com/nitro52/svelte-typescript-sass-template

it would be nice if i could figure out how to shared them between tsconfig and webpack but it is a step closer

**Comment by nitro52** [comment]
So i thought i had it all working but now it seems like the importer does not fall back to the default importers so i can no longer import sass from node_modules. I had a look at the sass importer docs and it looks like we should return null when we want it to fall back to another importer. However this didn't work. 

@kaisermann do you have any thoughts? I've uploaded an example to my [template](https://github.com/nitro52/svelte-typescript-sass-template). you just need to uncomment the `//@import "icons";` line in `styles/defaults.scss`

**Comment by kaisermann** [comment]
If I'm not mistaken, the `~` prefix is not a language standard, it's specific for the `sass-loader` (see [this](https://github.com/webpack-contrib/sass-loader/blob/master/src/importsToResolve.js#L12)). Your aliases and `node_modules` paths don't need to be prefixed with the `~`.  What matters here are your `includePaths` (paths files resolution) and `importer`. `svelte-preprocess` [automatically adds your `node_modules` to the `includePaths` array](https://github.com/kaisermann/svelte-preprocess/blob/master/src/utils.ts#L880)

**Comment by nitro52** [comment]
yes that's what i was basing it off. is the sass-loader not used under the hoods? 

Webstorm also expects you to use it which will give you better IDE support like CTRL+Click navigation and better auto complete

I was thinking i might need to resolve this manually but wasn't sure how to get access to the node_modules path. that helps though.
